version: "3.9"

services:
    db:
        image: postgres
        environment:
            POSTGRES_DB: dnastrands-db
            POSTGRES_USER: ijmazur
            POSTGRES_PASSWORD: asdfgh
        ports:
            - 5432:5432