# Generated by Django 3.2.12 on 2022-08-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_codes', models.TextField()),
                ('f1', models.TextField()),
                ('f2', models.TextField()),
                ('f3', models.TextField()),
                ('strand', models.TextField()),
            ],
        ),
    ]
