# Generated by Django 3.2.12 on 2022-09-27 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tag_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainappuser',
            name='date_of_birth',
        ),
    ]
