# Generated by Django 3.2.12 on 2022-10-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tag_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='verification_codes',
        ),
        migrations.AddField(
            model_name='tag',
            name='secret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
