# Generated by Django 3.2.13 on 2022-10-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tag_control_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='control_sum',
        ),
        migrations.AddField(
            model_name='tag',
            name='f1_f2',
            field=models.TextField(default='NULL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='primer_1',
            field=models.TextField(default='NULL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='primer_2',
            field=models.TextField(default='NULL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='primer_3',
            field=models.TextField(default='NULL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='scheme',
            field=models.TextField(default='NULL'),
            preserve_default=False,
        ),
    ]
